name: yahou_calender
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.9
  intl: ^0.19.0  # バージョンを0.19.0に更新
  flutter_riverpod: ^2.4.9
  uuid: ^4.5.1
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  timezone: ^0.9.2
  flutter_local_notifications: ^16.3.0
  http: ^1.1.0
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  google_sign_in: ^6.1.6
  icalendar_parser: ^2.0.0
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3  # バージョンを2.0.3に変更

flutter:
  uses-material-design: true
